#!/bin/bash -e
BASEDIR=$(readlink -f "$(dirname "$0")")
STACK="$1"
DATACENTER="$2"
METHOD="$3"
path="$4"
shift 4

if [ -z "$STACK" ] || [ -z "$DATACENTER" ]; then
    echo "usage: $BASEDIR/consul STACK DATACENTER GET|PUT|POST|DELETE CONSUL_PATH [ARGS]"
fi

CERTDIR="$HOME/.swarmer/vagrant/dev"
curl -vvv -k --fail \
     --cacert "$CERTDIR/ca.pem" \
     --cert "$CERTDIR/default.pem" \
     --key "$CERTDIR/default-key.pem" \
     -H "Host: toto" \
     -"X$METHOD" "https://consul.service.dev.vagrant:8500/v1$path" "$@"
