version: '2'
services:
  dnsmasq:
    image: andyshinn/dnsmasq
    command: -S /swarmer/${CONSULIP}#8600
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - SERVICE_IGNORE=true
