version: '2'
services:
  consul:
    image: voxxit/consul
    entrypoint: /bin/sh
    command: -c 'consul agent -data-dir /data -join 192.168.101.101 -dc vagrant -bind=0.0.0.0 -advertise=$$(ip route | grep default | sed "s/.*src \([0-9\.]*\).*$$/\1/g")'
    network_mode: host

  dnsmasq:
    image: andyshinn/dnsmasq
    command: -S /consul/127.0.0.1#8600
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - SERVICE_IGNORE=true
