version: '2'
services:
  namenode:
    image: uhopper/hadoop-namenode
    ports:
      - 50070
    expose:
      - 8020
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    networks:
      - hadoop
    volumes:
      - /hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hdfs-only

  datanode1:
    image: uhopper/hadoop-datanode
    hostname: datanode1
    container_name: datanode1
    domainname: hadoop
    depends_on:
      - namenode
    environment:
      - affinity:container!=*datanode*
    networks:
      - hadoop
    volumes:
      - /hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020

  datanode2:
    image: uhopper/hadoop-datanode
    hostname: datanode2
    container_name: datanode2
    domainname: hadoop
    depends_on:
      - namenode
    environment:
      - affinity:container!=*datanode*
    networks:
      - hadoop
    volumes:
      - /hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020

  datanode3:
    image: uhopper/hadoop-datanode
    hostname: datanode3
    container_name: datanode3
    domainname: hadoop
    depends_on:
      - namenode
    environment:
      - affinity:container!=*datanode*
    networks:
      - hadoop
    volumes:
      - /hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020

  datanode4:
    image: uhopper/hadoop-datanode
    hostname: datanode4
    container_name: datanode4
    domainname: hadoop
    depends_on:
      - namenode
    environment:
      - affinity:container!=*datanode*
    networks:
      - hadoop
    volumes:
      - /hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020

  datanode5:
    image: uhopper/hadoop-datanode
    hostname: datanode5
    container_name: datanode5
    domainname: hadoop
    depends_on:
      - namenode
    environment:
      - affinity:container!=*datanode*
    networks:
      - hadoop
    volumes:
      - /hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020



networks:
  hadoop:
