#!/bin/bash
REGISTRATOR_CONTAINER_NAME="registrator"
REGISTRATOR_VERSION="v6"
ADMIN_NETWORK="default"
PUBLIC_NETWORK="default"

if [[ -f "/etc/registrator/registrator.conf" ]]; then
    . /etc/registrator/registrator.conf
fi

verbose=0

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-hv] [-n CONTAINER_NAME] start|stop|join
Handles the lifecycle of a registrator service docker container

COMMANDS:
    start              Starts a registrator
    stop               Stops a registrator

OPTIONS:
    -h                 display this help and exit
    -n CONTAINER_NAME  sets the name of the docker container.
                       Defaults to $REGISTRATOR_CONTAINER_NAME
    -v                 verbose mode. Can be used multiple
                       times for increased verbosity.
EOF
}

servicename(){
    echo "${REGISTRATOR_CONTAINER_NAME}"
}

getpubipaddr(){
    # Keep trying to retrieve IP addr until it succeeds. Timeouts after 1m
    now=$(date +%s)
    timeout=$(( now + 60 ))
    set +e
    while :; do
        if [[ $timeout -lt $(date +%s) ]]; then
            logger -t "$SWARM_CONTAINER_NAME" "Could not retrieve IP Address. Exiting"
            exit 5
        fi
        ip route | grep -q "^$PUBLIC_NETWORK"
        [ $? -eq 0 ] && break
        sleep 1
    done

    printf "$(ip route | grep "^$PUBLIC_NETWORK" | sed 's/.*src \([0-9\.]*\) .*/\1/g')"
}

gethostadminipaddr(){
    # Keep trying to retrieve IP addr until it succeeds. Timeouts after 1m
    now=$(date +%s)
    timeout=$(( now + 60 ))
    set +e
    while :; do
        if [[ $timeout -lt $(date +%s) ]]; then
            logger -t "$SWARM_CONTAINER_NAME" "Could not retrieve IP Address. Exiting"
            exit 5
        fi
        ip route | grep -q "^$ADMIN_NETWORK"
        [ $? -eq 0 ] && break
        sleep 1
    done

    printf "$(ip route | grep "^$ADMIN_NETWORK" | sed 's/.*src \([0-9\.]*\) .*/\1/g')"
}

start() {
    stop
    /usr/bin/docker run \
                    -v /var/run/docker.sock:/tmp/docker.sock \
                    --name $(servicename) \
                    gliderlabs/registrator:${REGISTRATOR_VERSION} -ip=$(getpubipaddr) consul://$(gethostadminipaddr):8500 -resync 10 -ttl 10
}

stop() {
    if (docker ps | grep -q $(servicename)); then
        /usr/bin/docker stop -t 2 $(servicename) >&2
    fi
    if (docker ps -a | grep -q $(servicename)); then
        /usr/bin/docker rm $(servicename) >&2
    fi
}

OPTIND=1 # Reset is necessary if getopts was used previously in the script.  It is a good idea to make this local in a function.
while getopts ":hv:n:" opt; do
    case "$opt" in
        h)
            show_help
            exit 0
            ;;
        v)  verbose=$((verbose+1))
            ;;
        n)  REGISTRATOR_CONTAINER_NAME=$OPTARG
            ;;
        '?')
            show_help >&2
            exit 2
            ;;
    esac
done
shift "$((OPTIND-1))" # Shift off the options and optional --.

case $1 in
    start)
        logger -t "$(servicename)" "start"
        start
        ;;
    stop)
        logger -t "$(servicename)" "stop"
        stop
        ;;
    *)
        echo "unhandled command: $1" >&2
        exit 3
        ;;
esac
