module "swarm-cluster-single-zone" {
     source = "../swarm"
     count = "${var.count}"
     name = "${var.name}"
     key_name = "${var.key_name}"
     stack_name = "${var.stack_name}"
     subnet_id = "${var.subnet_id}"
     vpc_id = "${var.vpc_id}"
     security_group = "${var.security_group}"
     additional_docker_opts = "${var.additional_docker_opts}"
     instance_type = "${var.instance_type}"
     node_datasize = "${var.node_datasize}"
     node_ebs_optimized = "${var.node_ebs_optimized}"
     swarmer_ami = "${var.swarmer_ami}"
     swarm_mode = "both"
     consul_joinaddress = "${var.consul_joinaddress}"
     consul_mode = "server"
     admin_network = "${var.admin_network}"
     registry_access_key_id = "${var.registry_access_key_id}"
     registry_access_key_secret = "${var.registry_access_key_secret}"
     rexray_access_key_id = "${var.rexray_access_key_id}"
     rexray_access_key_secret = "${var.rexray_access_key_secret}"
     bucket = "${var.bucket}"
     aws_region= "${var.aws_region}"
}

module "swarm-cluster-single-zone-nodes" {
     source = "../swarm"
     count = "${var.additional_nodes}"
     name = "${var.name}"
     key_name = "${var.key_name}"
     stack_name = "${var.stack_name}"
     subnet_id = "${var.subnet_id}"
     vpc_id = "${var.vpc_id}"
     security_group = "${var.security_group}"
     additional_docker_opts = "${var.additional_docker_opts}"
     instance_type = "${var.instance_type}"
     node_datasize = "${var.node_datasize}"
     node_ebs_optimized = "${var.node_ebs_optimized}"
     swarmer_ami = "${var.swarmer_ami}"
     swarm_mode = "agent"
     consul_joinaddress = "${module.swarm-cluster-single-zone.join_address}"
     consul_mode = "agent"
     admin_network = "${var.admin_network}"
     registry_access_key_id = "${var.registry_access_key_id}"
     registry_access_key_secret = "${var.registry_access_key_secret}"
     rexray_access_key_id = "${var.rexray_access_key_id}"
     rexray_access_key_secret = "${var.rexray_access_key_secret}"
     bucket = "${var.bucket}"
     aws_region= "${var.aws_region}"
}
