#!/bin/bash
verbose=0

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-hv] [-n CONTAINER_NAME] start|stop
Starts|Stops haproxy

COMMANDS:
    start              Starts haproxy
    stop               Stops haproxy

OPTIONS:
    -h                 display this help and exit
    -v                 verbose mode. Can be used multiple
                       times for increased verbosity.
EOF
}

log(){
   logger -s -t "haproxy" -p $@
}

start() {
 log user.info "start"
}


stop() {
 log user.info "stop"
}

if [[ ! -f "/etc/swarmer/haproxy.yml" ]]; then
    log user.error "missing configuration file"
    exit 1
fi

OPTIND=1 # Reset is necessary if getopts was used previously in the script.  It is a good idea to make this local in a function.
while getopts ":hv:" opt; do
    case "$opt" in
        h)
            show_help
            exit 0
            ;;
        v)  verbose=$((verbose+1))
            ;;
        '?')
            show_help >&2
            exit 2
            ;;
    esac
done
shift "$((OPTIND-1))" # Shift off the options and optional --.

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "unhandled command: $1" >&2
        exit 3
        ;;
esac
