#!/bin/bash
if [ -f /etc/swarmer/swarmer.conf ]; then
    source /etc/swarmer/swarmer.conf
fi

BASEDIR="$(readlink -f $(dirname $0))/.."
CONTAINER_NAME=${CONTAINER_NAME:-"registry"}
ADMIN_NETWORK=${ADMIN_NETWORK:-"default"}
HOST_IP="$(ip route | grep $ADMIN_NETWORK | sed 's/.*src \([0-9\.]*\).*$/\1/g')"

SWARM_HOST=$HOST_IP:4000

registry-exists(){
    ID=$(docker -H $1 ps -q -a --filter label=private-registry)
    [[ $? -eq 0 ]] && [[ ! -z $ID ]]
}

registry-running(){
    ID=$(docker -H $1 ps -q --filter label=private-registry)
    [[ $? -eq 0 ]] && [[ ! -z $ID ]]
}

touch /etc/swarmer/registry.conf

export CONSUL_SESSION_ID=$(curl -XPUT "http://localhost:8500/v1/session/create" \
     -d '{"Name":"'$(hostname)'", "TTL": "120s", "LockDelay" : "120s"}' 2>/dev/null | jq '.ID' | sed 's/"//g' || exit 1)

LOCKED=$(curl -XPUT "http://localhost:8500/v1/kv/swarmer/start-registry-lock?acquire=$CONSUL_SESSION_ID" 2>/dev/null || exit 1)

exit_release(){
    curl -XPUT "http://localhost:8500/v1/kv/swarmer/start-registry-lock?release=$CONSUL_SESSION_ID" 2>/dev/null
    exit $1
}

if [[ "$LOCKED" != "true" ]]; then
    logger -s -p user.info $LOCKED
    logger -s -p user.info "start-registry-lock already acquired".
    exit_release 0
fi


if ! registry-exists $SWARM_HOST ; then
    docker create \
           -l private-registry \
           --name $CONTAINER_NAME \
           -p 5000:5000 \
           -e reschedule:on-node-failure \
           -e SERVICE_5000_CHECK_HTTP=/ \
           -e SERVICE_5000_CHECK_INTERVAL=15s \
           -e SERVICE_5000_CHECK_TIMEOUT=1s \
           -v /etc/docker/registry/config.yml:/etc/docker/registry/config.yml \
           registry:2 >&2 || exit_release 1
fi

if registry-exists $HOST_IP:2375; then
    if ! registry-running $HOST_IP:2375; then
        sudo docker start -a $CONTAINER_NAME >&2 || exit_release 1
    fi
else
    logger -s -p user.info "registry exists on another host. leaving." >&2
fi

exit_release 0
