#!/bin/bash
log(){
   logger -s -t "swarmer" -p "$@"
}

if [ ! -f /etc/swarmer/swarmer.conf ]; then
    log user.error "couldn't find configuration file"
    exit 1
fi

source /etc/swarmer/swarmer.conf
STACK_NAME=${STACK_NAME:-swarmer}
DATACENTER=${DATACENTER:-dev}

log user.info "init swarmer"
cp /etc/swarmer/certs/ca.pem /etc/ssl/certs/"$DATACENTER.$STACK_NAME".pem
update-ca-certificates
