#!/bin/bash
log(){
   logger -s -t "swarmer" -p "$@"
}
gethostadminipaddr(){
    # Keep trying to retrieve IP addr until it succeeds. Timeouts after 1m
    now=$(date +%s)
    timeout=$(( now + 60 ))
    set +e
    while :; do
        if [[ $timeout -lt $(date +%s) ]]; then
            log user.error "Could not retrieve IP Address. Exiting"
            exit 1
        fi
        ip route | grep -q "^$ADMIN_NETWORK"
        [ $? -eq 0 ] && break
        sleep 1
    done

    ip route | grep "^$ADMIN_NETWORK" | sed 's/.*src \([0-9\.]*\) .*/\1/g'
}

if [ ! -f /etc/swarmer/swarmer.conf ]; then
    log user.error "couldn't find configuration file"
    exit 1
fi

source /etc/swarmer/swarmer.conf
STACK_NAME=${STACK_NAME:-swarmer}
DATACENTER=${DATACENTER:-dev}

log user.info "init swarmer"

if [ ! -f /etc/swarmer/certs.tar.base64 ]; then
    log user.error "cannot find certificates."
    exit 1
fi

mkdir -p /etc/swarmer/certs
base64 -d < /etc/swarmer/certs.tar.base64 | tar -C /etc/swarmer/certs -xf -
cp /etc/swarmer/certs/cluster.crt /etc/ssl/certs/"$DATACENTER.$STACK_NAME".pem
update-ca-certificates


ADMIN_IP=$(gethostadminipaddr)
# force resolving admin services on local box to enable consul check services
echo "$ADMIN_IP swarm.service.$DATACENTER.$STACK_NAME consul.service.$DATACENTER.$STACK_NAME registry.service.$DATACENTER.${STACK_NAME}" | sudo tee -a /etc/hosts
