#!/bin/bash -e
if [[ -f "/etc/swarmer/swarmer.conf" ]]; then
    source /etc/swarmer/swarmer.conf
fi

SWARM_CONTAINER_NAME=${SWARM_CONTAINER_NAME:-swarm}
SWARM_MODE=${SWARM_MODE:-both}
ADMIN_NETWORK=${ADMIN_NETWORK:-default}
STACK_NAME=${STACK_NAME:-swarmer}
verbose=0

log(){
   logger -s -t "swarm-manager" -p "$@"
}

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-hv] start|stop|check|register|deregister|engine-ops
Handles the lifecycle of a swarm manager

COMMANDS:
    start              Starts a swarm manager
    stop               Stops a swarm manager
    engine-opts        Echo engine opts
    register           Registers manager in consul
    deregister         Deregisters manager in consul
    check              Checks if manager is running

OPTIONS:
    -h                 display this help and exit
    -v                 verbose mode. Can be used multiple
                       times for increased verbosity.
EOF
}

gethostadminipaddr(){
    # Keep trying to retrieve IP addr until it succeeds. Timeouts after 1m
    now=$(date +%s)
    timeout=$(( now + 60 ))
    set +e
    while :; do
        if [[ $timeout -lt $(date +%s) ]]; then
            log user.error "Could not retrieve IP Address. Exiting"
            exit 1
        fi
        ip route | grep -q "^$ADMIN_NETWORK"
        [ $? -eq 0 ] && break
        sleep 1
    done

    ip route | grep "^$ADMIN_NETWORK" | sed 's/.*src \([0-9\.]*\) .*/\1/g'
}

engine_opts(){
    IP=$(gethostadminipaddr)
    echo "-H tcp://$IP:2376 --tlsverify --tlscacert=/etc/swarmer/certs/ca.pem --tlscert=/etc/swarmer/certs/docker.pem --tlskey=/etc/swarmer/certs/docker-key.pem --cluster-store=consul://consul.service.$DATACENTER.$STACK_NAME:8500 --cluster-store-opt kv.cacertfile=/etc/swarmer/certs/ca.pem --cluster-store-opt kv.certfile=/etc/swarmer/certs/default.pem --cluster-store-opt kv.keyfile=/etc/swarmer/certs/default-key.pem --cluster-advertise=$IP:2376"
}

start(){
    log user.info "start"
    IP=$(gethostadminipaddr)
    rkt run \
        --net=host \
        --volume hosts,kind=host,source=/etc/hosts,readOnly=true \
        --volume certs,kind=host,source=/etc/swarmer/certs,readOnly=true \
        --volume data,kind=host,source=/var/lib/swarm-manager,readOnly=false \
        --mount volume=hosts,target=/etc/hosts \
        --mount volume=certs,target=/certs \
        --mount volume=data,target=/.swarm \
        --uuid-file-save /var/run/swarm-manager.uuid \
        swarm --exec /swarm -- \
        manage --host 0.0.0.0:4000 --replication --advertise "$(hostname).node.$DATACENTER.$STACK_NAME":4000 \
        --tlsverify \
        --tlscacert=/certs/ca.pem \
        --tlscert=/certs/docker.pem \
        --tlskey=/certs/docker-key.pem \
        --discovery-opt kv.cacertfile=/certs/ca.pem \
        --discovery-opt kv.certfile=/certs/default.pem \
        --discovery-opt kv.keyfile=/certs/default-key.pem \
        "consul://consul.service.$DATACENTER.$STACK_NAME:8500/swarm"
}

register(){
    #registers in consul
    TMPFILE=$(mktemp)
    cat > "$TMPFILE" <<EOF
{
  "ID":"swarm-$(hostname)",
  "Name": "swarm",
  "Address": "$IP",
  "Port": 4000,
  "Check": {
    "Script": "/opt/swarmer/swarm-manager-manage",
    "Interval": "10s"
  }
}
EOF
    curl --fail \
         --cacert /etc/swarmer/certs/ca.pem \
         --cert /etc/swarmer/certs/default.pem \
         --key /etc/swarmer/certs/default-key.pem \
         -XPUT "https://consul.service.$DATACENTER.$STACK_NAME:8500/v1/agent/service/register" -d @"$TMPFILE" 2>/dev/null
    rm "$TMPFILE"
}


deregister(){
    #deregisters in consul
    consul PUT "/agent/service/deregister/swarm-$(hostname)" 2>/dev/null
}

check(){
    /usr/bin/curl --fail \
         --cacert /etc/swarmer/certs/ca.pem \
         --cert /etc/swarmer/certs/docker.pem \
         --key /etc/swarmer/certs/docker-key.pem \
         -XGET "https://swarm.service.$DATACENTER.${STACK_NAME}:4000/_ping"
}

stop() {
    log user.info "stop"
    if [ -f /var/run/swarm-manager.uuid ]; then
        sudo machinectl kill "rkt-$(cat /var/run/swarm-manager.uuid)"
    fi
}

if [ "$SWARM_MODE" != "manager" ] && [ "$SWARM_MODE" != "both" ]; then
    log user.info "not a swarm manager node: nothing to do."
    exit 0
fi

mkdir -p /var/lib/swarm-manager

OPTIND=1 # Reset is necessary if getopts was used previously in the script.  It is a good idea to make this local in a function.
while getopts ":hv:n:" opt; do
    case "$opt" in
        h)
            show_help
            exit 0
            ;;
        v)  verbose=$((verbose+1))
            ;;
        '?')
            show_help >&2
            exit 2
            ;;
    esac
done

shift "$((OPTIND-1))" # Shift off the options and optional --.

case $1 in
    engine-opts)
        engine_opts
        ;;
    start)
        start
        ;;
    stop)
        stop
        ;;
    check)
        check
        ;;
    register)
        register
        ;;
    deregister)
        deregister
        ;;
    *)
        check
        ;;
esac
