#!/bin/bash -e
BASEDIR=$(readlink -f "$(dirname "$0")")
STACK="$1"
DATACENTER="$2"

if [ -z "$STACK" ] || [ -z "$DATACENTER" ]; then
    echo "usage: $BASEDIR/swarmer.sh STACK DATACENTER"
    exit 1
fi

CERTDIR="$HOME/.swarmer/$STACK/$DATACENTER"
mkdir -p "$CERTDIR"

if [ ! -z "$(find $CERTDIR -type f)" ]; then
    echo "$CERTDIR is not empty."
    exit 1
fi

cat > "$CERTDIR"/run.sh <<EOF
cd /certs
echo '{"CN":"$DATACENTER $STACK","key":{"algo":"rsa","size":4096}}' | cfssl gencert -initca - | cfssljson -bare ca -

echo '{"signing":{"default":{"expiry":"100000h","usages":["signing","client auth"]}}}' > req-docker.json
echo '{"CN":"$DATACENTER $STACK default","hosts":["consul.service.dev.vagrant","registry.service.dev.vagrant","swarm.service.dev.vagrant"],"key":{"algo":"rsa","size":4096}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=req-docker.json - | cfssljson -bare docker

echo '{"signing":{"default":{"expiry":"100000h","usages":["signing","server auth","client auth"]}}}' > req-default.json
echo '{"CN":"$DATACENTER $STACK default","hosts":["consul.service.dev.vagrant","registry.service.dev.vagrant","swarm.service.dev.vagrant"],"key":{"algo":"rsa","size":4096}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=req-default.json - | cfssljson -bare default

#echo '{"CN":"","hosts":[],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json - | cfssljson -bare client
EOF

chmod +x "$CERTDIR/run.sh"
docker run --rm -v "$CERTDIR":/certs --entrypoint /bin/bash cfssl/cfssl -c "/certs/run.sh > /dev/null"

sudo chown -R "$USER":"$USER" "$CERTDIR"
find "$CERTDIR" -type f -exec chmod 0600 {} \;

pushd "$CERTDIR" >/dev/null

# We don't want to ship the cacert with the tarball.
# Plus no one should be able to create new certs.
rm -f ca-key.pem run.sh
cp default.pem docker.pem
cp default-key.pem docker-key.pem
echo "Generating PKCS12 cert to use in browser"
openssl pkcs12 -inkey default-key.pem -in default.pem -export -out default.pfx
tar -cf "./certs.tar" ./*.pem
popd >/dev/null

base64 > "$CERTDIR/certs.$DATACENTER.$STACK.tar.base64" < "$CERTDIR/certs.tar"

rm "$CERTDIR/certs.tar"

echo "certs are in $(readlink -f "$CERTDIR")"
