#!/bin/bash
BASEDIR=$(readlink -f "$(dirname "$0")")
STACK="$1"
shift
DATACENTER="$1"
shift

if [ -z "$STACK" ] || [ -z "$DATACENTER" ]; then
    echo "usage: $BASEDIR/swarmer.sh STACK DATACENTER [docker commands]"
fi

if [ ! -d "$HOME/.swarmer/$STACK/$DATACENTER" ]; then
    echo "$STACK/$DATACENTER is not present in $HOME/.swarmer. Generate the certificates with:" >&2
    echo "$BASEDIR/certs.sh $STACK $DATACENTER" >&2
    exit 1
fi

HOST="swarm.service.$DATACENTER.$STACK:4000"
docker run --rm -it --net host -v "$HOME/.swarmer/$STACK/$DATACENTER":/certs:ro docker:1.10 -H "$HOST" --tlsverify --tlscacert /certs/ca.pem --tlscert /certs/default.pem --tlskey /certs/default-key.pem "$@"
